Updated Layer5 projects in the list
collabnix/kubetools pull request #263
Opened 2024-02-01 14:40 UTC by saurabh100ni

### PR Description
This PR fixes #262

2024-02-01 19:38 UTC, iArchitSharma requested changes

2024-02-01 19:38 UTC, iArchitSharma commented on README.md
> +| 41 |	Meshery | [ Meshery by Layer5 is a cloud native manager, extracting maximum value from your infrastructure ](https://github.com/meshery/meshery) | ![Github Stars](https://img.shields.io/github
Please update the Meshery description

2024-02-01 23:52 UTC, saurabh100ni commented on README.md
> +| 41 |	Meshery | [ Meshery by Layer5 is a cloud native manager, extracting maximum value from your infrastructure ](https://github.com/meshery/meshery) | ![Github Stars](https://img.shields.io/github
Done @iArchitSharma

2024-02-02 10:16 UTC, merged

2024-02-02 10:17 UTC, apurvabhandari commented
Thanks @saurabh100ni @iArchitSharma